server:
  port: 5050
  servlet:
    context-path: /api
#websocket接口
ws:
  port: 5051
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easychat?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: easyJavaPool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    jedis:
      pool:
        max-active: 20
        max-wait: 1
        max-idle: 10
        min-idle: 0
    timeout: 2000
#项目目录
project:
  folder: d:/webser/web_app/easychat/
log:
  root:
    level: debug
admin:
  emails: 1965564484@qq.com
#是否是开发环境
dev: false

